export const signupApi = "https://easybuyapi.adaptable.app/api/v1/auth/signup"
export const loginApi = "https://easybuyapi.adaptable.app/api/v1/auth/login"
export const baseUrl = "https://easybuyapi.adaptable.app/api/v1"
export const getReferral = "https://easybuyapi.adaptable.app/api/v1/auth/referral"
export const vtpassBaseApi = "https://api-service.vtpass.com/api"
export const localUrl = "http://localhost:5000/api/v1"